apiVersion: batch/v1
kind: Job
metadata:
  name: indexer
spec:
  template:
    metadata:
      name: indexer
    spec:
      containers:
      - name: indexer
        image: "python:3"
        command:
         - "/bin/sh" 
         - "-c"
         - "pip install -r requirements/requirements.txt && python script/hn.py"
        env: 
        - name: ELASTICSEARCH_HOST
          value: spa-search-api-elasticsearch-client
        volumeMounts: 
        - name: script
          mountPath: /script
        - name: requirements
          mountPath: /requirements
      volumes: 
      - name: script
        configMap: 
          name: hn
      - name: requirements
        configMap: 
          name: requirements
      restartPolicy: Never


